apiVersion: v1
kind: Service
metadata:
  name: genztech-service
  labels:
    app: regapp
spec:
  selector:
    app: regapp

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer
